// <auto-generated />
using System;
using FruitPort.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FruitPort.Infrastructure.Migrations;

[DbContext(typeof(FruitContext))]
[Migration("20241207133320_RemoveActionFromStock")]
partial class RemoveActionFromStock
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("FruitPort.Infrastructure.FruitStock", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("ActionDate")
                    .HasColumnType("datetime2");

                b.Property<int>("FruitTypeId")
                    .HasColumnType("int");

                b.Property<int>("Quantity")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("FruitTypeId");

                b.ToTable("FruitStocks");
            });

        modelBuilder.Entity("FruitPort.Infrastructure.FruitType", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("ExpiryDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Origin")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<decimal>("PurchasePrice")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal>("SalePrice")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.ToTable("FruitTypes");
            });

        modelBuilder.Entity("FruitPort.Infrastructure.FruitStock", b =>
            {
                b.HasOne("FruitPort.Infrastructure.FruitType", "FruitType")
                    .WithMany("StockEntries")
                    .HasForeignKey("FruitTypeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("FruitType");
            });

        modelBuilder.Entity("FruitPort.Infrastructure.FruitType", b =>
            {
                b.Navigation("StockEntries");
            });
#pragma warning restore 612, 618
    }
}
